kind: pipeline
name: Built Bot

steps:
- name: ROM
  image: baalajimaestro/android_build:latest
  environment:
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
    TELEGRAM_CHAT:
      from_secret: TELEGRAM_CHAT
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
  commands:
  - echo test   
  - git config --global user.email "soniataran79@gmail.com"
  - git config --global user.name "aman25502"
  - cd /home/ci
  - mkdir "testl"
  - cd "testl"
  - repo init -u https://github.com/Legionrom/platform_manifest.git -b q
  - repo sync -c --force-sync --no-clone-bundle -j8

